IMAGE_PREFIX="igorlg"
IMAGE_NAME="git-server"
IMAGE_VERSION="latest"

CONTAINER_NAME="$IMAGE_NAME"
EXPOSE_SSH_PORT=2222

VOLUME_PREFIX="/nas/GitServer"
VOLUME_DATA_PATH="${VOLUME_PREFIX}/data"
VOLUME_CONFIG_PATH="${VOLUME_PREFIX}/sshd_config"
VOLUME_KEYS_PATH="${VOLUME_PREFIX}/authorized_keys"

