#!/bin/ash

# Common
IMAGE_NAME="git-server"
IMAGE_PREFIX="igorlg"
IMAGE_VERSION="latest"
CONTAINER_NAME="$IMAGE_NAME"

# Run
CONTAINER_EXPOSE_SSH_PORT=2222
CONTAINER_GIT_PATH="/git"
VOLUME_PREFIX="/nas/GitServer"
VOLUME_DATA_PATH="${VOLUME_PREFIX}/data"
VOLUME_KEYS_PATH="${VOLUME_PREFIX}/authorized_keys"
# VOLUME_CONFIG_PATH="${VOLUME_PREFIX}/sshd_config"

