#!/bin/ash

if [ -z "$1" ]; then
        echo "Repository name not informed. Exiting"
        exit 120
fi

if [ -d "/git/${1}.git" ]; then
        echo "Repository ${1} already exists"
        exit 121
fi

git_path="${CONTAINER_GIT_PATH:-/git}"

git init --bare ${git_path}/${1}.git

$HOME/list

