#!/bin/ash

if [ -z "$1" ]; then
        echo "Repository name not informed. Exiting"
        exit 120
fi

repo_name="${1}"
echo $repo_name | grep -e "\.git$" >/dev/null 2>&1 || repo_name="${repo_name}.git"

git_path="${CONTAINER_GIT_PATH:-/git}"
if [ -d "${git_path}/${repo_name}" ]; then
        echo "Repository ${repo_name} already exists"
        exit 121
fi

git init --bare ${git_path}/${repo_name}

$(dirname $(realpath $0))/list

